### ISSUE TITLE
Connection lost between Broker and Database

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-catalogue#27]
After a period of 48 hours (weekend) the connection between broker and database is lost;

**Comment by Endebert** [comment]
Do you have any logs I can look into? I think this issue will be fixed in 1.1.0 when we use the new leshan version (because it sends a client update every minute), but it would still be great if we could find out why the connection is lost in the current version.

**Comment by Endebert** [comment]
Should be fixed in new [release 1.1.0](https://github.com/reTHINK-project/dev-catalogue/releases/tag/1.1.0)

**Comment by vitormsilva** [comment]
Hi @Endebert,

I think this problem presists.. i upload the 2 log files..

[catalogue-broker.txt](https://github.com/reTHINK-project/dev-catalogue/files/277255/catalogue-broker.txt)
[catalogue-database.txt](https://github.com/reTHINK-project/dev-catalogue/files/277256/catalogue-database.txt)

In Friday all works fine, but today, I have no communication with catalogue database.

If you need something else, let me know.

**Comment by Endebert** [comment]
Thanks for the logs. From what I can tell, it seems that you are not using the latest version of the broker and database.

If you are using and building the docker images from /docker/, please do a `docker pull` for both rethink/catalogue-broker and rethink/catalogue-database.

[Additionally, I just pushed a small fix, because the in the docker folder the `idpproxy` folders were not renamed yet.](https://github.com/reTHINK-project/dev-catalogue/commit/166a1728bdd355843b0b4c4329146ea489ce8e56) So please also do a git pull before bulding the image, or manually rename the folder `idpproxy` to `idp-proxy`

**Comment by Endebert** [comment]
No update, so I'm closing this issue
