### ISSUE TITLE
Starting catalogue-broker error

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-catalogue#39]
Hi @Endebert,

I try to start the catalogue.. and i have the following message: [catalogue-broker.txt](https://github.com/reTHINK-project/dev-catalogue/files/386241/catalogue-broker.txt)

I start the broker in the same way as before..
Could you help me?

**Comment by Endebert** [comment]
Could you please provide the error log again, it seems the link provided does not point to a broker log

**Comment by vitormsilva** [comment]
yes.. sorry i don't know what happened

[catalogue-broker.txt](https://github.com/reTHINK-project/dev-catalogue/files/386266/catalogue-broker.txt)

**Comment by Endebert** [comment]
I don't really know what's going on there, if possible could you please start the broker with the -vv option?

It sounds like a problem related to the catalogue objects on the database. Is there anything suspicious in the log of the Catalogue Database? Try to run that with -vv, too, and send me the logs

**Comment by vitormsilva** [comment]
I hope this can help:

[catalogue-broker.txt](https://github.com/reTHINK-project/dev-catalogue/files/386305/catalogue-broker.txt)

**Comment by Endebert** [comment]
Ok from what I can tell, the resource requested is ok, but the broker seems to have trouble decoding the response from the Catalogue Database.

I can also see that you updated the Catalogue Broker, but not the Catalogue Database.

Could you please update the Catalogue Database and try again, I believe this would fix the problem.

**Comment by vitormsilva** [comment]
I have update the database too.. i think..

```shell
docker images   
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
ptnode_catalogue-database-ptinovacao        latest              68f34a699b3f        About an hour ago   752.4 MB
rethink/catalogue-broker                    latest              f354543e00e7        4 hours ago         750.3 MB
rethink/catalogue-database-rethinkdefault   latest              6ef4b08b8edd        5 hours ago         752.4 MB
node                                        latest              9121f2a78909        5 weeks ago         659.3 MB
```
Ok.. i will do it again.. could solve the problem..

**Comment by vitormsilva** [comment]
I update the database and solve the problem.. but now we are facing other issue.. the catalogue-broker starts but i can't access it;

Docker images are updated
```
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
ptnode_catalogue-database-ptinovacao        latest              ead246062085        9 minutes ago       752.8 MB
rethink/catalogue-broker                    latest              50f32f8c00b9        About an hour ago   750.4 MB
rethink/catalogue-database-rethinkdefault   latest              081676022ee1        About an hour ago   752.8 MB
```
the log file: 
[catalogue-broker.txt](https://github.com/reTHINK-project/dev-catalogue/files/386545/catalogue-broker.txt)

**Comment by Endebert** [comment]
Hmm this could be a result of the new way the Catalogue Broker is configured. Because now, the default settings include the Broker hostname, which was unset in the old version by default. Now the default hostname is "localhost", which might be the source of the problem.

There are 2 ways we can try to solve this issue:

1. specify a hostname
  * use the -host option to set the hostname. This could be the hostname of the machine (e.g. "catalogue.hybroker.rethink.ptinovacao.pt") or the IP (e.g. "172.18.0.9") and see if that fixes the problem (I found those values in old issues, don't know if they fit your current environment)
2. use the configuration file to set the hostname to null
  * I'm not sure if this will work, but you could try creating a file in the root folder of the catalogue named "brokerconf.json" and use this as the contents:
  ```
  {
    "host": null
  }
  ```
  * if this actually sets the host variable to null (check the broker log), it should emulate the behaviour of the older Broker versions

**Comment by vitormsilva** [comment]
@Endebert

I use the `-host` option, and seems working, at least on my machine.
I think i can close the issue.

Thank you;
