### ISSUE TITLE
default catalogue has no protostub example

### ISSUE THREAD

**Issue by sbecot** [reTHINK-project/dev-catalogue#51]
I suggest to insert a protostub folder here:
https://github.com/reTHINK-project/dev-catalogue/tree/master/docker/catalogue-database-reTHINKdefault/catalogue_objects
including up to date versions of the protostubs of developped messaging nodes to facilitate plateform deployment.

**Comment by emmelmann-fokus** [comment]
no objections from my part.  @Endebert what do you think?

**Comment by Endebert** [comment]
I added the Vertx Protostub we use in our testbed that is working.

I also added the NodeJS Protostub that is already included in /docker/catalogue-database-reTHINK-HelloWorld, but I don't know how up-to-date this version is. I think its best if the people responsible for the various protostubs should provide the necessary source code that is supposed to be served by the Catalogue.

Could someone please contact the people responsible for the protostubs listed below, so that they may push a current/working version into the folder?

* https://github.com/reTHINK-project/dev-msg-node-vertx
* https://github.com/reTHINK-project/dev-msg-node-nomatrix
* https://github.com/reTHINK-project/dev-msg-node-matrix
* https://github.com/reTHINK-project/dev-msg-node-nodejs

**Comment by sbecot** [comment]
Thank you. 
No the nodejs is not up to date, and I'm currently trying to solve this with APIzee. I agree that the protostubs should be published here by the responsible of the code.

**Comment by jboulmal** [comment]
We have updated it. However, we haven't provided it in the catalogue.
We will do it soon do some fixes and push it to the appropriate  catalogue.

**Comment by sdruesedow** [comment]
I added the MatrixProtoStub/ folder to the dev branch. The included stub works for Matrix MN as well as for the new NoMatrix MN.

**Comment by Endebert** [comment]
Could everyone responsible for any of the listed msg nodes add a check if you have added a current version of the msg node to the rethinkdefault catalogue database:

- [ ] https://github.com/reTHINK-project/dev-msg-node-vertx
- [ ] https://github.com/reTHINK-project/dev-msg-node-nomatrix
- [ ] https://github.com/reTHINK-project/dev-msg-node-matrix
- [ ] https://github.com/reTHINK-project/dev-msg-node-nodejs

We would like to check if we can close this issue.

**Comment by sdruesedow** [comment]
done  for "matrix" and "nomatrix"

**Comment by jboulmal** [comment]
Already done for msg-node-nodejs [here](https://github.com/reTHINK-project/dev-catalogue/tree/master/docker/catalogue-database-reTHINKdefault/catalogue_objects/protocolstub/NodejsProtoStub)

**Comment by Endebert** [comment]
Assuming this can be closed.
