### ISSUE TITLE
Constraints Matching Problems

### ISSUE THREAD

**Issue by luistduarte** [reTHINK-project/dev-catalogue#62]
For example when we have one hyperty like HelloWorldObserver. Their constraints are  `"constraints": { "browser": true }`. Normally our device Capabilities when we are using a "normal" laptop are `"constraints": { "browser": true, "windowSandbox": true, "mic": true, "camera": true }`.

So if the hyperty got only these contraints and our request is with our capabilities, We can't found this hyperty because our RuntimeUA is more "powerfull" than hypertie requirements.
![screenshot from 2017-03-13 13 19 22](https://cloud.githubusercontent.com/assets/11315256/23855992/bfbb0036-07ef-11e7-819a-8a9a3efa9ef6.png)

**Comment by pchainho** [comment]
Constraints defined in the descriptor identifies capabilities required by the runtime. If no constraints are defined, it means the component can be deployed on any runtime independently of its capabilities.

Only descriptors that explicitly set constraints ie `<constraint> : true` have to be matched with runtime capabilities present in the runtime catalogue request.

**Comment by Endebert** [comment]
It is clear to me that this cannot work. Because e.g. you want `"windowSandbox": true`, but the hyperty doesn't guarantee that it supports/provides this functionality, therefore it is not being returned.

As I said before, this is _matching_ constraints. [I also described this in the initial issue](https://github.com/reTHINK-project/specs/issues/13): 

> Please provide feedback on how this constraint matching is supposed to work. For example, when we look at how getUserMedia() is handled in browsers, constraints can be defined as mandatory or optional. I believe reducing our constraints to only include mandatory entries would suffice, but I would like to hear what you think.
>
> __What I mean by mandatory only constraints, is that, if a user requests a default descriptor with some constraints, all of them have to be fulfilled by a "constraint set" defined in the broker config, in order to be chosen. But, a "constraint set" in the config can have more entries than than what the user has requested.__

Since you never said you needed optional constraints, it was never implemented.

> Only descriptors that explicitly set constraints ie <constraint> : true have to be matched with runtime capabilities present in the runtime catalogue request.

This I don't fully understand. So you only want the constraints in your POST request only be matched if  there is a flag in the descriptor you want to check for a match? Why not simply send an empty body?

**Comment by pchainho** [comment]
> Since you never said you needed optional constraints, it was never implemented.

I don't think it is a question of supporting optional constraints since all constraints defined in the descriptors are mandatory. 

For example, the descriptor of one protostub that is deployable in the Browser Runtime, has defined as constraints: `{ "browser": true }`

This catalogue object should only be returned when requested by the runtime catalogue, if the payload "constraints" contains  `"browser": true`, for example like this one:

 `"constraints": { "browser": true, "windowSandbox": true, "mic": true, "camera": true }`

On the other side, if the descriptor of one protostub that is only deployable in the Nodejs Runtime, has defined as constraints: `{ "node": true }`

This catalogue object should only be returned when requested by the runtime catalogue, if the payload "constraints" contains  `"node": true`, for example like this one:

 `"constraints": { "node": true }`

> Or is this simply "We want this feature the other way around"?

Not sure what you mean, but "constraints" are from the perspective of the catalogue object ie defines the capabilities to be supported by the runtime in order to be able to deploy and execute the catalogue object in the runtime.

**Comment by Endebert** [comment]
> Not sure what you mean, but "constraints" are from the perspective of the catalogue object ie defines the capabilities to be supported by the runtime in order to be able to deploy and execute the catalogue object in the runtime.

Thanks for clearing this up. Because I always interpreted them as being from the perspective of the runtime, i.e. "I want a hyperty that fulfills these criteria".

Fortunately, inverting the functionality seems to be an easy task. I will have a look at it.

**Comment by pchainho** [comment]
Great, thx

**Comment by Endebert** [comment]
@pchainho @luistduarte I have updated the Catalogue Broker (both dev and master branch)

Please pull the new image when ready and test it. Since I increased the version number, you can verify having the correct version when looking at the Catalogue Broker version in the log.

**Comment by luistduarte** [comment]
I will try this afternoon, thanks Robert

**Comment by luistduarte** [comment]
The first impression was good, tomorrow I make more tests and i can close this issue, if everything is alright
